### ISSUE TITLE
where can I download co saliency image pair dataset?

### ISSUE THREAD

**Issue by adityaksai** [aunnnn/CORSaliency#1]
The original website is not working.	
It is Co-saliency image pair dataset. Dataset consists of 210 images. http://ivipc.uestc.edu.cn/hlli/projects/cosaliency.html
please help me

**Comment by aunnnn** [comment]
Hi adityaksai,

I think you might mistaken the 'cosalieny' model with the model in this repository, which is 'CORSaliency'. So I recommend you contact the authors of the paper instead.
